apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: productservice
  name: productservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: productservice
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: productservice
    spec:
      containers:
      - image: mail4dhananjaya/productservice:latest
        name: productservice
        resources: {}
status: {}
